/**
 * A Godot 4 project, generated whole.
 *
 * The target is the Godot Android editor: a user opens the extracted folder on
 * their phone and presses play. That sets the bar — a project that imports but
 * does not run is a failed build, the same rule the Minecraft suite follows.
 *
 * Three things decide whether it runs, and each has been got wrong by hand
 * before:
 *   - `project.godot` must declare a `config_version` and a `run/main_scene`
 *     that actually exists, or Godot opens an empty editor;
 *   - a `.tscn` header's `load_steps` must match the number of resources in the
 *     file, or the scene loads with missing nodes;
 *   - every `ExtResource` id referenced by a node must be declared above it.
 *
 * Pure: returns a file map. Zipping and downloading happen elsewhere.
 */

export interface GodotFile {
  path: string;
  content: string;
}

export interface GameSpec {
  /** Shown in the Godot project list and the window title. */
  name: string;
  /** 3D is the default; a 2D game uses Node2D and a different camera. */
  dimension?: '2d' | '3d';
  /** Models to place in the scene, as res:// paths to .glb files. */
  models?: Array<{
    path: string;
    node: string;
    at?: [number, number, number];
    /**
     * A skinned model with a skeleton. Parented to the player and given the
     * animation script, so it walks rather than standing there.
     */
    rigged?: boolean;
  }>;
}

/** Godot's own identifier rules: a folder name that will not need escaping. */
export function projectFolder(name: string): string {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 48);
  return slug || 'chomugiri_game';
}

/**
 * A deterministic uid for a scene.
 *
 * Godot writes `uid://` ids into every scene and resource. They only have to be
 * unique within the project, and a stable one keeps regenerated projects from
 * churning — but two scenes sharing one makes Godot drop the second.
 */
export function sceneUid(seed: string): string {
  // Godot's uids are base-36-ish; any distinct token in that alphabet works.
  let hash = 0x811c9dc5;
  for (let i = 0; i < seed.length; i += 1) {
    hash ^= seed.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return `uid://c${hash.toString(36)}${seed.length.toString(36)}`;
}

/**
 * `project.godot`.
 *
 * `renderer/rendering_method="mobile"` matters here: the Forward+ default does
 * not run on most phones, and the editor this is opened in *is* a phone. The
 * gl_compatibility fallback covers older hardware.
 */
export function projectConfig(spec: GameSpec): string {
  return `; Generated by Chomugiri.
; Godot reads this to find the project. config_version 5 is Godot 4.x.

config_version=5

[application]

config/name="${spec.name.replace(/"/g, '\\"')}"
run/main_scene="res://main.tscn"
config/features=PackedStringArray("4.3", "Mobile")
config/icon="res://icon.svg"

[display]

window/size/viewport_width=1152
window/size/viewport_height=648
window/handheld/orientation=1
window/stretch/mode="canvas_items"
window/stretch/aspect="expand"

[input]

move_left={
"deadzone": 0.2,
"events": [Object(InputEventKey,"keycode":65,"pressed":true)]
}
move_right={
"deadzone": 0.2,
"events": [Object(InputEventKey,"keycode":68,"pressed":true)]
}
move_forward={
"deadzone": 0.2,
"events": [Object(InputEventKey,"keycode":87,"pressed":true)]
}
move_back={
"deadzone": 0.2,
"events": [Object(InputEventKey,"keycode":83,"pressed":true)]
}
jump={
"deadzone": 0.2,
"events": [Object(InputEventKey,"keycode":32,"pressed":true)]
}

[rendering]

renderer/rendering_method="mobile"
renderer/rendering_method.mobile="gl_compatibility"
textures/vram_compression/import_etc2_astc=true
`;
}

/** A placeholder icon, so the project list does not show a broken thumbnail. */
export function projectIcon(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128">
  <rect width="128" height="128" rx="24" fill="#e8722a"/>
  <path d="M40 84V44l24 14 24-14v40" fill="none" stroke="#fff" stroke-width="9" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
`;
}

/**
 * The player controller.
 *
 * Written for touch as much as keys, because this runs on a phone: the virtual
 * joystick in the scene drives the same movement the keys do, rather than a
 * second code path that can rot.
 */
export function playerScript(): string {
  return `extends CharacterBody3D
## Player movement. Touch drag and WASD both feed the same vector,
## so there is only one path to keep working.

@export var speed: float = 5.0
@export var jump_velocity: float = 4.5

var touch_direction := Vector2.ZERO


func _physics_process(delta: float) -> void:
	# Gravity from the project setting, so changing it in one place works.
	if not is_on_floor():
		velocity += get_gravity() * delta

	if Input.is_action_just_pressed("jump") and is_on_floor():
		velocity.y = jump_velocity

	var input := Input.get_vector("move_left", "move_right", "move_forward", "move_back")
	if input == Vector2.ZERO:
		input = touch_direction

	var direction := (transform.basis * Vector3(input.x, 0.0, input.y)).normalized()
	if direction:
		velocity.x = direction.x * speed
		velocity.z = direction.z * speed
	else:
		# move_toward rather than a hard zero, so stopping is not a jolt.
		velocity.x = move_toward(velocity.x, 0.0, speed)
		velocity.z = move_toward(velocity.z, 0.0, speed)

	move_and_slide()


func _on_joystick_moved(direction: Vector2) -> void:
	touch_direction = direction
`;
}

/** An on-screen stick, because a phone has no WASD. */
export function joystickScript(): string {
  return `extends Control
## A thumb stick for touch. Emits a normalised direction the player reads.

signal moved(direction: Vector2)

@export var radius: float = 110.0

var _touch_index := -1
var _centre := Vector2.ZERO


func _gui_input(event: InputEvent) -> void:
	if event is InputEventScreenTouch:
		if event.pressed and _touch_index == -1:
			_touch_index = event.index
			_centre = event.position as Vector2
		elif not event.pressed and event.index == _touch_index:
			_touch_index = -1
			moved.emit(Vector2.ZERO)
			queue_redraw()
	elif event is InputEventScreenDrag and event.index == _touch_index:
		# Typed explicitly: Godot cannot infer a type through an event property,
		# and := there is a parse error, not a warning.
		var offset: Vector2 = event.position - _centre
		# Clamped, then normalised by the radius: a small drag should not be
		# the same as a full one.
		moved.emit(offset.limit_length(radius) / radius)
		queue_redraw()


func _draw() -> void:
	if _touch_index == -1:
		return
	draw_circle(_centre, radius, Color(1, 1, 1, 0.12))
	draw_circle(_centre, radius * 0.4, Color(1, 1, 1, 0.35))
`;
}

/**
 * Animation for a rigged character.
 *
 * Procedural rather than a baked AnimationPlayer, deliberately. A hand-written
 * .tscn animation has to name every track by node path and bone index, and a
 * single wrong index animates nothing with no error anywhere. This reads the
 * skeleton at runtime: bones it cannot find are skipped, so a model rigged as a
 * quadruped — or not rigged at all — degrades to standing still instead of
 * crashing.
 *
 * The cycle is driven by how fast the body is actually moving, so the legs do
 * not skate while the character stands still.
 */
export function characterScript(): string {
  return `extends Node3D
## Drives a skinned character's bones from its parent's velocity.
## Attach to the imported .glb node; the parent should be a CharacterBody3D.

@export var swing: float = 0.9        ## Radians a limb swings at full speed.
@export var steps_per_metre: float = 0.55

var _skeleton: Skeleton3D
var _body: CharacterBody3D
var _phase: float = 0.0
## Bone indices, resolved once. -1 means this rig does not have that bone.
var _bones := {}


func _ready() -> void:
	_skeleton = _find_skeleton(self)
	if _skeleton == null:
		# Not a rigged model. Nothing to drive, and nothing to complain about.
		set_physics_process(false)
		return

	_body = get_parent() as CharacterBody3D
	for name in ["ArmL", "ArmR", "LegL", "LegR", "Chest", "Head"]:
		_bones[name] = _skeleton.find_bone(name)


func _find_skeleton(node: Node) -> Skeleton3D:
	if node is Skeleton3D:
		return node
	for child in node.get_children():
		var found := _find_skeleton(child)
		if found != null:
			return found
	return null


func _rotate_bone(bone_name: String, axis: Vector3, angle: float) -> void:
	var index: int = _bones.get(bone_name, -1)
	if index < 0:
		return
	# Rest is the bind pose; posing relative to it keeps the limb attached.
	_skeleton.set_bone_pose_rotation(index, Quaternion(axis, angle))


func _physics_process(delta: float) -> void:
	var speed := 0.0
	if _body != null:
		speed = Vector2(_body.velocity.x, _body.velocity.z).length()

	if speed > 0.05:
		_phase += delta * speed * steps_per_metre * TAU
	else:
		# Settle back to the rest pose instead of freezing mid-stride.
		_phase = move_toward(_phase, round(_phase / TAU) * TAU, delta * 6.0)

	var reach := swing * clampf(speed / 5.0, 0.0, 1.0)
	var stride := sin(_phase) * reach

	# Arms and legs swing opposite each other; left and right are out of phase.
	_rotate_bone("LegL", Vector3.RIGHT, stride)
	_rotate_bone("LegR", Vector3.RIGHT, -stride)
	_rotate_bone("ArmL", Vector3.RIGHT, -stride)
	_rotate_bone("ArmR", Vector3.RIGHT, stride)
	# A small counter-rotation in the chest stops it reading as a puppet.
	_rotate_bone("Chest", Vector3.UP, stride * 0.12)
`;
}

/**
 * The main scene.
 *
 * `load_steps` counts every ext_resource and sub_resource plus one. Godot uses
 * it to size its load table, and a wrong count is the classic reason a
 * hand-written .tscn opens with nodes missing.
 */
export function mainScene(spec: GameSpec): string {
  const models = spec.models ?? [];

  const rigged = models.filter((m) => m.rigged);

  const ext: string[] = [
    `[ext_resource type="Script" path="res://player.gd" id="1_player"]`,
    `[ext_resource type="Script" path="res://joystick.gd" id="2_stick"]`,
  ];
  // Declared only when something uses it: an ext_resource pointing at a file
  // the project does not contain stops the scene loading.
  if (rigged.length) ext.push(`[ext_resource type="Script" path="res://character.gd" id="3_character"]`);

  const modelIdBase = ext.length + 1;
  models.forEach((model, i) => {
    ext.push(`[ext_resource type="PackedScene" path="${model.path}" id="${modelIdBase + i}_model${i}"]`);
  });

  const sub = [
    `[sub_resource type="BoxMesh" id="BoxMesh_ground"]
size = Vector3(40, 0.5, 40)`,
    `[sub_resource type="BoxShape3D" id="BoxShape3D_ground"]
size = Vector3(40, 0.5, 40)`,
    `[sub_resource type="CapsuleShape3D" id="CapsuleShape3D_player"]
height = 2.0
radius = 0.4`,
    `[sub_resource type="StandardMaterial3D" id="StandardMaterial3D_ground"]
albedo_color = Color(0.36, 0.47, 0.31, 1)`,
  ];

  const loadSteps = ext.length + sub.length + 1;

  // A rigged model is the player's body, so it hangs off the Player node and
  // gets the animation script. Everything else is scenery placed in the world.
  const sceneryNodes = models
    .map((model, i) => {
      if (model.rigged) return null;
      const [x, y, z] = model.at ?? [0, 0, 0];
      return `[node name="${model.node}" parent="." instance=ExtResource("${modelIdBase + i}_model${i}")]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, ${x}, ${y}, ${z})`;
    })
    .filter((node): node is string => node !== null)
    .join('\n\n');

  const riggedNodes = models
    .map((model, i) => {
      if (!model.rigged) return null;
      // Dropped by half the capsule height so the feet meet the floor rather
      // than hovering at the body's centre.
      return `[node name="${model.node}" parent="Player" instance=ExtResource("${modelIdBase + i}_model${i}")]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, -1, 0)
script = ExtResource("3_character")`;
    })
    .filter((node): node is string => node !== null)
    .join('\n\n');

  return `[gd_scene load_steps=${loadSteps} format=3 uid="${sceneUid(spec.name)}"]

${ext.join('\n')}

${sub.join('\n\n')}

[node name="Main" type="Node3D"]

[node name="Sun" type="DirectionalLight3D" parent="."]
transform = Transform3D(0.87, -0.35, 0.35, 0, 0.7, 0.71, -0.5, -0.61, 0.61, 0, 12, 0)
shadow_enabled = true

[node name="Environment" type="WorldEnvironment" parent="."]

[node name="Ground" type="StaticBody3D" parent="."]

[node name="Mesh" type="MeshInstance3D" parent="Ground"]
mesh = SubResource("BoxMesh_ground")
material_override = SubResource("StandardMaterial3D_ground")

[node name="Collision" type="CollisionShape3D" parent="Ground"]
shape = SubResource("BoxShape3D_ground")

[node name="Player" type="CharacterBody3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1.5, 0)
script = ExtResource("1_player")

[node name="Collision" type="CollisionShape3D" parent="Player"]
shape = SubResource("CapsuleShape3D_player")

[node name="Camera" type="Camera3D" parent="Player"]
transform = Transform3D(1, 0, 0, 0, 0.92, 0.39, 0, -0.39, 0.92, 0, 2.2, 6)

${riggedNodes}

${sceneryNodes}

[node name="UI" type="CanvasLayer" parent="."]

[node name="Joystick" type="Control" parent="UI"]
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
script = ExtResource("2_stick")

[connection signal="moved" from="UI/Joystick" to="Player" method="_on_joystick_moved"]
`;
}

/** A README, because the user opens this on a phone and needs to know where to start. */
export function readme(spec: GameSpec): string {
  return `# ${spec.name}

A Godot 4 project, generated by Chomugiri.

## Opening it on Android

1. Extract this zip somewhere the Godot editor can reach — Internal storage is
   simplest, Downloads is fine.
2. Open **Godot Engine 4** and press **Import**.
3. Point it at the extracted folder and pick \`project.godot\`.
4. Press **Play** (▶). \`main.tscn\` runs.

## What is here

| File | What it does |
| --- | --- |
| \`project.godot\` | Project settings. Renderer is set to mobile, which is what runs on a phone. |
| \`main.tscn\` | The scene that runs: ground, light, player, camera and the touch stick. |
| \`player.gd\` | Movement. Touch drag and WASD feed the same vector. |
| \`joystick.gd\` | The on-screen stick. |
${(spec.models ?? []).some((m) => m.rigged) ? '| `character.gd` | Swings the rigged character\'s arms and legs from how fast it is moving. |\n' : ''}${(spec.models ?? [])
    .map((m) =>
      m.rigged
        ? `| \`${m.path.replace('res://', '')}\` | A rigged character with a skeleton, attached to the player as **${m.node}**. |`
        : `| \`${m.path.replace('res://', '')}\` | A generated model, placed as **${m.node}**. |`,
    )
    .join('\n')}

## Changing it

The player moves at \`speed\` and jumps at \`jump_velocity\` — both are exported,
so they are editable in the inspector without touching code.
`;
}

/** Every file the project needs, ready to zip. */
export function buildProject(spec: GameSpec): GodotFile[] {
  const files: GodotFile[] = [
    { path: 'project.godot', content: projectConfig(spec) },
    { path: 'icon.svg', content: projectIcon() },
    { path: 'main.tscn', content: mainScene(spec) },
    { path: 'player.gd', content: playerScript() },
    { path: 'joystick.gd', content: joystickScript() },
    { path: 'README.md', content: readme(spec) },
  ];
  if ((spec.models ?? []).some((m) => m.rigged)) {
    files.push({ path: 'character.gd', content: characterScript() });
  }
  return files;
}

/**
 * What would stop this project from running.
 *
 * Checked rather than assumed, because every one of these has shipped broken
 * from a hand-written project at some point.
 */
export function validateProject(files: GodotFile[]): string[] {
  const problems: string[] = [];
  const byPath = new Map(files.map((f) => [f.path, f.content]));

  const config = byPath.get('project.godot');
  if (!config) {
    problems.push('No project.godot — Godot will not recognise this as a project at all.');
    return problems;
  }
  if (!/^config_version=\d+/m.test(config)) {
    problems.push('project.godot has no config_version; Godot refuses to import it.');
  }

  const mainScene = /run\/main_scene="res:\/\/([^"]+)"/.exec(config)?.[1];
  if (!mainScene) problems.push('project.godot names no main scene, so pressing play does nothing.');
  else if (!byPath.has(mainScene)) problems.push(`Main scene "${mainScene}" is referenced but not in the project.`);

  for (const [path, content] of byPath) {
    if (!path.endsWith('.tscn')) continue;

    const header = /^\[gd_scene load_steps=(\d+) format=3/.exec(content);
    if (!header) {
      problems.push(`${path} has no valid [gd_scene] header.`);
      continue;
    }

    const resources = (content.match(/^\[(ext_resource|sub_resource)/gm) ?? []).length;
    const declared = Number(header[1]);
    if (declared !== resources + 1) {
      problems.push(`${path}: load_steps is ${declared} but the scene has ${resources} resources — it should be ${resources + 1}.`);
    }

    // Every referenced id must be declared, or the node loads without it.
    const declaredIds = new Set([...content.matchAll(/^\[ext_resource[^\]]*id="([^"]+)"/gm)].map((m) => m[1]));
    for (const match of content.matchAll(/ExtResource\("([^"]+)"\)/g)) {
      if (!declaredIds.has(match[1])) problems.push(`${path} uses ExtResource("${match[1]}") which is never declared.`);
    }

    const declaredSubs = new Set([...content.matchAll(/^\[sub_resource[^\]]*id="([^"]+)"/gm)].map((m) => m[1]));
    for (const match of content.matchAll(/SubResource\("([^"]+)"\)/g)) {
      if (!declaredSubs.has(match[1])) problems.push(`${path} uses SubResource("${match[1]}") which is never declared.`);
    }

    // A script path that does not exist leaves the node inert at runtime.
    for (const match of content.matchAll(/\[ext_resource type="Script" path="res:\/\/([^"]+)"/g)) {
      if (!byPath.has(match[1])) problems.push(`${path} points at script "${match[1]}", which is not in the project.`);
    }
  }

  return problems;
}
